name: WebPortal Docker Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  #docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:latest
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:latest,${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:${{ github.run_number }}
          
  deploy-desenvolvimento:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Run commands on remote host
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USER }}
        port: ${{ vars.PORT }}
        key: ${{ secrets.K8S_CLUSTER_SSH_KEY_PAIR }}
        debug: true
        script_stop: true
        script: |
          whoami
          ls -al