name: Publish Docker image

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:latest
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:latest,${{ secrets.DOCKERHUB_USERNAME }}/eventos-static:${{ github.run_number }}
          
  deploy-desenvolvimento:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - name: Run commands on remote host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          port: ${{ vars.PORT }}
          key: ${{ secrets.K8S_CLUSTER_SSH_KEY_PAIR }}
          script_stop: true
          script: |
            cd ~/APPS-NAMESPACE/eventos/
            wget -q --show-progress --progress=bar:force:noscroll \
            -O manifests.yaml \
            https://raw.githubusercontent.com/glauccop/WebPortal/main/k8s/manifests.yaml
            kubectl apply -f manifests.yaml
            sleep 5
            kubectl -n eventos get deploy -o wide
            kubectl -n eventos get pods -o wide
            kubectl -n eventos get svc -o wide
            kubectl -n eventos get ing
